### ISSUE TITLE
server.log request and session id are missing from lnav config

### ISSUE THREAD

**Issue by stefer** [curityio/lnav#1]
It seems like all of these variants can exist:

`2017-09-20T07:26:11:444+0000` DEBUG   {conf-Thread-12-39} se.curity.identityserver.logging.Log4jAuditEventLogger

2017-09-20T07:26:11:444+0000 DEBUG  efdd8765 {conf-Thread-12-39} se.curity.identityserver.logging.Log4jAuditEventLogger

2017-09-20T07:26:11:444+0000 DEBUG abcf4567 efdd8765 {conf-Thread-12-39} se.curity.identityserver.logging.Log4jAuditEventLogger`

It seem to be some kind of reference, related to the thread id, maybe a unique hash per request?
log4j settings are:
`
 <Console name="stdout" target="SYSTEM_OUT">
            <PatternLayout noConsoleNoAnsi="true" pattern="%date{yyyy-MM-dd'T'HH:mm:ss:SSSZ} %highlight{%-5level}{FATAL=blink bright red, ERROR=bright red, WARN=yellow, INFO=green, DEBUG=cyan, TRACE=white} %X{RequestId} %X{SessionId} %highlight{{%thread}}{FATAL=white, ERROR=white, WARN=white, INFO=white, DEBUG=white, TRACE=white} %highlight{%logger - %msg%n}{FATAL=blink bright red, ERROR=bright red, WARN=yellow, INFO=green, DEBUG=cyan, TRACE=white}"/>
            <filters>
                <MarkerFilter marker="REQUEST" onMatch="DENY" onMismatch="NEUTRAL"/>
                <MarkerFilter marker="EXTENDED_REQUEST" onMatch="DENY" onMismatch="NEUTRAL"/>
            </filters>
        </Console>
`

**Comment by travisspencer** [comment]
I submitted a fix for this, @stefer . Can you confirm that the latest on master is working for you?
