### ISSUE TITLE
cluster.log timestamp format has changed

### ISSUE THREAD

**Issue by stefer** [curityio/lnav#2]
lnav specification does not match pattern in log4j

`
 <RollingFile name="cluster-log" fileName="${env:IDSVR_HOME}/var/log/cluster.log"
                     filePattern="${env:IDSVR_HOME}/var/log/cluster.log.%i.gz">
            <Policies>
                <SizeBasedTriggeringPolicy size="10MB"/>
            </Policies>
            <DefaultRolloverStrategy max="5"/>
            <PatternLayout pattern="%date{yyyy-MM-dd'T'HH:mm:ss:SSSZ} %-5level {%thread} %logger - %msg%n"/>
        </RollingFile>

`

**Comment by travisspencer** [comment]
this is fixed in e767701a01c2b274d319ae2df5589db50ef838e9. Can you confirm that it's working OK for you? If so, I'll close this issue.

**Comment by stefer** [comment]
It looks good, travis. I will have a look at it when I am back at work.
We have managed to ship these logs to Elastic now, so we do not use the lnav tool that much anymore.
It was very handy, though.
